ALTER TABLE tiktok_accounts
ADD COLUMN IF NOT EXISTS follower_count INTEGER,
ADD COLUMN IF NOT EXISTS following_count INTEGER,
ADD COLUMN IF NOT EXISTS likes_count INTEGER,
ADD COLUMN IF NOT EXISTS video_count INTEGER;