create table
    public.account_analytics (
        id bigint generated by default as identity,
        tiktok_account_id uuid not null,
        follower_count integer not null,
        following_count integer not null,
        likes_count integer not null,
        video_count integer not null,
        created_at timestamp
        with
            time zone not null default now (),
            constraint account_analytics_pkey primary key (id),
            constraint account_analytics_tiktok_account_id_fkey foreign key (tiktok_account_id) references tiktok_accounts (id) on update cascade on delete cascade
    ) tablespace pg_default;

alter table public.account_analytics enable row level security;

create policy "Enable read access for authenticated users" on public.account_analytics for
select
    using (auth.role () = 'authenticated');

alter table public.tiktok_accounts
drop column if exists follower_count;

alter table public.tiktok_accounts
drop column if exists following_count;

alter table public.tiktok_accounts
drop column if exists likes_count;

alter table public.tiktok_accounts
drop column if exists video_count;