create table
    public.tiktok_accounts (
        id bigint generated by default as identity not null,
        user_id uuid not null,
        name text null,
        auth_token text null,
        created_at timestamp
        with
            time zone not null default now (),
            constraint tiktok_accounts_pkey primary key (id),
            constraint tiktok_accounts_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade
    ) tablespace pg_default;